scss_files: "**/*.scss"
linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false
  BorderZero:
    enabled: false
    convention: zero
  ColorKeyword:
    enabled: false
  ColorVariable:
    enabled: false
  Comment:
    enabled: false
  DebugStatement:
    enabled: true
  DeclarationOrder:
    enabled: true
  DuplicateProperty:
    enabled: true # NOTE disabled for fallback properties
  ElsePlacement:
    enabled: true
    style: same_line
  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true
  EmptyRule:
    enabled: true
  FinalNewline:
    enabled: true
    present: true
  HexLength:
    enabled: false
    style: short
  HexNotation:
    enabled: true
    style: lowercase
  HexValidation:
    enabled: true
  IdSelector:
    enabled: true
  ImportantRule:
    enabled: true # NOTE disabled for aesop inline overrides
  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false
  Indentation:
    enabled: false
  LeadingZero:
    enabled: true
    style: exclude_zero
  MergeableSelector:
    enabled: true
    force_nesting: true
  NameFormat:
    enabled: true
    allow_leading_underscore: true
    convention: hyphenated_lowercase
  NestingDepth:
    enabled: true # NOTE hound ci seems to confuse scss nesting with actual generated css nesting.
  PlaceholderInExtend:
    enabled: false
  PropertyCount:
    enabled: false
  PropertySortOrder:
    enabled: true
    ignore_unspecified: false
    severity: warning
    separate_groups: false
  PropertySpelling:
    enabled: true
    extra_properties: []
  QualifyingElement:
    enabled: false
  SelectorDepth:
    enabled: true
    max_depth: 3 # NOTE increased for plugin overrides
    severity: warning
  SelectorFormat:
    enabled: true # NOTE disabled for disqus and lasso
  Shorthand:
    enabled: true
    severity: warning
  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true
  SingleLinePerSelector:
    enabled: true
  SpaceAfterComma:
    enabled: true
  SpaceAfterPropertyColon:
    enabled: true
    style: one_space
  SpaceAfterPropertyName:
    enabled: true
  SpaceBeforeBrace:
    enabled: true # NOTE disabled for "social-icon" mixin
  SpaceBetweenParens:
    enabled: true
    spaces: 0
  StringQuotes:
    enabled: true
    style: single_quotes
  TrailingSemicolon:
    enabled: true
  TrailingZero:
    enabled: false
  UnnecessaryMantissa:
    enabled: true
  UnnecessaryParentReference:
    enabled: true
  UrlFormat:
    enabled: true
  UrlQuotes:
    enabled: true
  VariableForProperty:
    enabled: false
    properties: []
  VendorPrefixes:
    enabled: true
    identifier_list: bourbon
    include: []
    exclude: []
  ZeroUnit:
    enabled: true
    severity: warning
  Compass::PropertyWithMixin:
    enabled: false
